### ISSUE TITLE
Cannot find panda_arm_with_dyn_params.xacro

### ISSUE THREAD

**Issue by th1991-01** [shamilmamedov/beam_handling#1]
HI,

I am interested in this research and would like to run the code.
When running [optimal_handling.py](https://github.com/shamilmamedov/beam_handling/blob/main/beam_handling_py/optimal_handling.py), `js_opt_traj_4rviz.csv` and `js_opt_traj.csv` are generated with dispalying Ipopt print, but he program stops with showing the following error.

```
redefining global symbol: pi
when processing file: /home/th1991-01/beam_handling-main/beam_handling_ws/src/bh_setup/urdf/setup_descr_pend_fixed.xacro
No such file or directory: /opt/ros/melodic/share/franka_description/robots/panda_arm_with_dyn_params.xacro [Errno 2] No such file or directory: u'/opt/ros/melodic/share/franka_description/robots/panda_arm_with_dyn_params.xacro'
when processing file: /home/th1991-01/beam_handling-main/beam_handling_ws/src/bh_setup/urdf/setup_descr_pend_fixed.xacro
RLException: Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/home/th1991-01/beam_handling-main/beam_handling_ws/src/bh_setup/urdf/setup_descr_pend_fixed.xacro']] returned with code [2].
Param xml is <param command="$(find xacro)/xacro '$(find bh_setup)/urdf/setup_descr_pend_fixed.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file
```

The error message seems to say that `panda_arm_with_dyn_params.xacro` is needed. but I cannot find it in this repository and https://github.com/frankaemika/franka_ros/tree/melodic-devel. Where can I get it?

Thanks in advance.

**Comment by shamilmamedov** [comment]
Hi there! I attached the file you are looking for. Actually you don't really need it to visualize the motion. I used this file to simulate the dynamics which you don't need here. You can replace `panda_arm_with_dyn_params.xacro` with `panda_arm.xacro`.

Feel free to ask if you have additional question.

[panda_arm_with_dyn_params.zip](https://github.com/shamilmamedov/beam_handling/files/13322465/panda_arm_with_dyn_params.zip)

**Comment by th1991-01** [comment]
Thank you so much! After putting this file in the path and modifying [this line](https://github.com/shamilmamedov/beam_handling/blob/bcd397f0ee02f0ae0cd806fdb3ae1a3e6330a07b/beam_handling_ws/src/bh_setup/state_pub.py#L26), the program works fine.
